# Generated by Django 5.2.6 on 2025-09-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='plan',
            new_name='goal',
        ),
    ]
