# Generated by Django 5.2.6 on 2025-09-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_plan_workout_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(blank=True, help_text='В секундах', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('reps', 'Повторения'), ('time', 'Время')], default='reps', max_length=10),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Тяжелая')], default='easy', max_length=50),
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, upload_to='workouts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
